username: BET4924170
password: Happyshare4us!
location: queensbridge-sports-community-centre
activity: badminton-40min
keyword: "Court 1,Court 3"
day: 7
slots:
  - start_time: "10:20"
    end_time: "11:00"
  - start_time: "11:00"
    end_time: "11:40"
  - start_time: "11:40"
    end_time: "12:20"