name: Deploy Lambda via CDK

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest

      - name: Run code formatter
        run: black src tests

      - name: Run integration tests
        run: |
          export PYTHONPATH=$PYTHONPATH:./src
          pytest tests/integration

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./cdk

      - name: Install AWS CDK
        run: npm install -g aws-cdk
        working-directory: ./cdk

      - name: CDK Synth
        run: cdk synth
        working-directory: ./cdk

      - name: CDK Deploy
        run: cdk deploy --all --require-approval never
        working-directory: ./cdk